name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: rust-binary
        path: target/release/gpt_bot

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: rust-binary
        path: target/release/gpt_bot

    - name: Deploy to server
      run: |
        scp target/release/gpt_bot ${{ secrets.SERVER_IP }}:/gpt_bot
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock

    - name: Restart service
      run: |
        ssh ${{ secrets.SERVER_IP }} "sudo systemctl restart gpt_bot"
